FROM node:lts-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your application's code to the container
COPY . .

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run the application using nodemon
CMD ["npm", "run", "dev"]